### PR TITLE
Interoperability with Selenium 4

### PR DESCRIPTION
**Pull request by mabartos**

### CODE REVIEW

**Review by asolntsev — APPROVED** [review]

**Comment by mabartos** [comment]
@asolntsev Thanks for quick merge! Is it possible to release new version of the driver?

**Comment by asolntsev** [comment]
Sure, I will release it asap.
Thank you for the contribution!

P.S. Why do you need phantomjsdriver when it can be easily replaced by headless chrome or Firefox?

**Comment by mabartos** [comment]
@asolntsev Thanks! It's used in [arquillian-extension-drone](https://github.com/arquillian/arquillian-extension-drone) testsuite and I'd like to keep it there :)

**Comment by asolntsev** [comment]
@mabartos I have released phantomjsdriver 1.5.0, it has already arrived to maven central repo:

```
testImplementation "com.codeborne:phantomjsdriver:1.5.0"
```

**Comment by mabartos** [comment]
@asolntsev Thanks!

**Pull request merged**
